//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Kinect.Toolkit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Kinect.Toolkit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter of type {0} not of of expected type {1}.
        /// </summary>
        internal static string DelegateCommandCastException {
            get {
                return ResourceManager.GetString("DelegateCommandCastException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All set!.
        /// </summary>
        internal static string MessageAllSet {
            get {
                return ResourceManager.GetString("MessageAllSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect is listening.
        /// </summary>
        internal static string MessageAllSetListening {
            get {
                return ResourceManager.GetString("MessageAllSetListening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Kinect is being used by another application..
        /// </summary>
        internal static string MessageConflict {
            get {
                return ResourceManager.GetString("MessageConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops, there is an error..
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing....
        /// </summary>
        internal static string MessageInitializing {
            get {
                return ResourceManager.GetString("MessageInitializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many USB devices! Please unplug one or more..
        /// </summary>
        internal static string MessageInsufficientBandwidth {
            get {
                return ResourceManager.GetString("MessageInsufficientBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect required.
        /// </summary>
        internal static string MessageNoAvailableSensors {
            get {
                return ResourceManager.GetString("MessageNoAvailableSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This sensor is not genuine!.
        /// </summary>
        internal static string MessageNotGenuine {
            get {
                return ResourceManager.GetString("MessageNotGenuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plug my power cord in!.
        /// </summary>
        internal static string MessageNotPowered {
            get {
                return ResourceManager.GetString("MessageNotPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinect for Xbox not supported..
        /// </summary>
        internal static string MessageNotSupported {
            get {
                return ResourceManager.GetString("MessageNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application needs a Kinect for Windows sensor in order to function. However, another application is using the Kinect Sensor..
        /// </summary>
        internal static string MoreInformationConflict {
            get {
                return ResourceManager.GetString("MoreInformationConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kinect Sensor is plugged in, however an error has occurred. For steps to resolve, please click the &quot;Help&quot; link..
        /// </summary>
        internal static string MoreInformationError {
            get {
                return ResourceManager.GetString("MoreInformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kinect Sensor needs the majority of the USB Bandwidth of a USB Controller. If other devices are in contention for that bandwidth, the Kinect Sensor may not be able to function..
        /// </summary>
        internal static string MoreInformationInsufficientBandwidth {
            get {
                return ResourceManager.GetString("MoreInformationInsufficientBandwidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application needs a Kinect for Windows sensor in order to function. Please plug one into the PC..
        /// </summary>
        internal static string MoreInformationNoAvailableSensors {
            get {
                return ResourceManager.GetString("MoreInformationNoAvailableSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application needs a genuine Kinect for Windows sensor in order to function. Please plug one into the PC..
        /// </summary>
        internal static string MoreInformationNotGenuine {
            get {
                return ResourceManager.GetString("MoreInformationNotGenuine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Kinect Sensor is plugged into the computer with its USB connection, but the power plug appears to be not powered..
        /// </summary>
        internal static string MoreInformationNotPowered {
            get {
                return ResourceManager.GetString("MoreInformationNotPowered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This application needs a Kinect for Windows sensor in order to function. Please plug one into the PC..
        /// </summary>
        internal static string MoreInformationNotSupported {
            get {
                return ResourceManager.GetString("MoreInformationNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to launch the default web browser. Trying to navigate to: {0}.
        /// </summary>
        internal static string NoDefaultBrowserAvailable {
            get {
                return ResourceManager.GetString("NoDefaultBrowserAvailable", resourceCulture);
            }
        }
    }
}
